# todo https://www.youtube.com/watch?v=qS9KYTcWMlY

version: '3'

volumes:
  redis_cache:
    driver: local
  postgres_db:
    driver: local

services:
  app:
    build:
      context: .
    container_name: SpringBootForum
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - '8080:8080'

  db:
    image: postgres:15.1
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_cache:/var/lib/redis/data