version: '3'

services:
  app:
    build:
      context: .
    container_name: SpringBootForum
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}

  db:
    image: postgres:15.1
    container_name: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    volumes:
      - postgres_db:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    container_name: redis
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis_cache:/var/lib/redis/data

volumes:
  redis_cache:
    driver: local
  postgres_db:
    driver: local