spring:
  messages:
    basename: language, site
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 10
        max-page-size: 500
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_forum
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
#        javax:
#          persistence:
#            sharedCache:
#              mode: ENABLE_SELECTIVE
#        javax.cache:
#          provider: org.ehcache.jsr107.EhcacheCachingProvider
        highlight_sql: true
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: validate
#        cache:
#          use_second_level_cache: true
#          jcache:
#            config:
#              classpath=ehcache.xml
#          use_query_cache: true
#          region_prefix: dd_hibernate
#          region:
#              factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory